// Character naming system for RoleLang
// Provides culturally appropriate names for each supported language

const characterNames = {
  English: {
    female: [
      ["Emma", "Johnson"], ["Olivia", "Smith"], ["Ava", "Williams"], ["Isabella", "Brown"],
      ["Sophia", "Jones"], ["Charlotte", "Garcia"], ["Mia", "Miller"], ["Amelia", "Davis"],
      ["Harper", "Rodriguez"], ["Evelyn", "Martinez"], ["Abigail", "Hernandez"], ["Emily", "Lopez"],
      ["Elizabeth", "Gonzalez"], ["Mila", "Wilson"], ["Ella", "Anderson"], ["Avery", "Thomas"],
      ["Sofia", "Taylor"], ["Camila", "Moore"], ["Aria", "Jackson"], ["Scarlett", "Martin"],
      ["Victoria", "Lee"], ["Madison", "Perez"], ["Luna", "Thompson"], ["Grace", "White"],
      ["Chloe", "Harris"], ["Penelope", "Sanchez"], ["Layla", "Clark"], ["Riley", "Ramirez"],
      ["Zoey", "Lewis"], ["Nora", "Robinson"], ["Lily", "Walker"], ["Eleanor", "Young"],
      ["Hannah", "Allen"], ["Lillian", "King"], ["Addison", "Wright"], ["Aubrey", "Scott"],
      ["Ellie", "Torres"], ["Stella", "Nguyen"], ["Natalie", "Hill"], ["Zoe", "Flores"],
      ["Leah", "Green"], ["Hazel", "Adams"], ["Violet", "Nelson"], ["Aurora", "Baker"],
      ["Savannah", "Hall"], ["Brooklyn", "Rivera"], ["Bella", "Campbell"], ["Claire", "Mitchell"],
      ["Skylar", "Carter"], ["Lucy", "Roberts"], ["Paisley", "Gomez"], ["Everly", "Phillips"],
      ["Anna", "Evans"], ["Caroline", "Turner"], ["Nova", "Diaz"], ["Genesis", "Parker"],
      ["Emilia", "Cruz"], ["Kennedy", "Edwards"], ["Samantha", "Collins"], ["Maya", "Stewart"],
      ["Willow", "Morris"], ["Kinsley", "Morales"], ["Naomi", "Murphy"], ["Aaliyah", "Cook"],
      ["Elena", "Rogers"], ["Sarah", "Gutierrez"], ["Ariana", "Ortiz"], ["Allison", "Morgan"],
      ["Gabriella", "Cooper"], ["Alice", "Peterson"], ["Madelyn", "Bailey"], ["Cora", "Reed"],
      ["Ruby", "Kelly"], ["Eva", "Howard"], ["Serenity", "Ramos"], ["Autumn", "Kim"],
      ["Adeline", "Cox"], ["Hailey", "Ward"], ["Gianna", "Richardson"], ["Valentina", "Watson"],
      ["Isla", "Brooks"], ["Eliana", "Chavez"], ["Quinn", "Wood"], ["Nevaeh", "James"],
      ["Ivy", "Bennett"], ["Sadie", "Gray"], ["Piper", "Mendoza"], ["Lydia", "Ruiz"],
      ["Alexa", "Hughes"], ["Josephine", "Price"], ["Emery", "Alvarez"], ["Julia", "Castillo"],
      ["Delilah", "Sanders"], ["Arianna", "Patel"], ["Vivian", "Myers"], ["Kaylee", "Long"],
      ["Sophie", "Ross"], ["Brielle", "Foster"], ["Madeline", "Jimenez"], ["Peyton", "Powell"],
      ["Rylee", "Jenkins"], ["Clara", "Perry"], ["Hadley", "Russell"], ["Melanie", "Sullivan"],
      ["Mackenzie", "Ford"], ["Reagan", "Hamilton"], ["Adalynn", "Graham"], ["Liliana", "Wallace"],
      ["Aubree", "Cole"], ["Jade", "West"], ["Kayla", "Jordan"], ["Jordyn", "Owens"],
      ["Melody", "Reynolds"], ["Iris", "Fisher"], ["Rose", "Ellis"], ["Juliana", "Harrison"],
      ["Laila", "Gibson"], ["Maria", "Mcdonald"], ["Esther", "Cruz"], ["Sylvia", "Marshall"],
      ["Raelynn", "Ortiz"], ["Arya", "Gomez"], ["Athena", "Murray"], ["Andrea", "Freeman"],
      ["Jasmine", "Wells"], ["Everleigh", "Webb"], ["Taylor", "Simpson"], ["Valeria", "Stevens"]
    ],
    male: [
      ["Liam", "Johnson"], ["Noah", "Smith"], ["Oliver", "Williams"], ["Elijah", "Brown"],
      ["William", "Jones"], ["James", "Garcia"], ["Benjamin", "Miller"], ["Lucas", "Davis"],
      ["Henry", "Rodriguez"], ["Alexander", "Martinez"], ["Mason", "Hernandez"], ["Michael", "Lopez"],
      ["Ethan", "Gonzalez"], ["Daniel", "Wilson"], ["Jacob", "Anderson"], ["Logan", "Thomas"],
      ["Jackson", "Taylor"], ["Levi", "Moore"], ["Sebastian", "Jackson"], ["Mateo", "Martin"],
      ["Jack", "Lee"], ["Owen", "Perez"], ["Theodore", "Thompson"], ["Aiden", "White"],
      ["Samuel", "Harris"], ["Joseph", "Sanchez"], ["John", "Clark"], ["David", "Ramirez"],
      ["Wyatt", "Lewis"], ["Matthew", "Robinson"], ["Luke", "Walker"], ["Asher", "Young"],
      ["Carter", "Allen"], ["Julian", "King"], ["Grayson", "Wright"], ["Leo", "Scott"],
      ["Jayden", "Torres"], ["Gabriel", "Nguyen"], ["Isaac", "Hill"], ["Lincoln", "Flores"],
      ["Anthony", "Green"], ["Hudson", "Adams"], ["Dylan", "Nelson"], ["Ezra", "Baker"],
      ["Thomas", "Hall"], ["Charles", "Rivera"], ["Christopher", "Campbell"], ["Jaxon", "Mitchell"],
      ["Maverick", "Carter"], ["Josiah", "Roberts"], ["Isaiah", "Gomez"], ["Andrew", "Phillips"],
      ["Elias", "Evans"], ["Joshua", "Turner"], ["Nathan", "Diaz"], ["Caleb", "Parker"],
      ["Ryan", "Cruz"], ["Adrian", "Edwards"], ["Miles", "Collins"], ["Eli", "Stewart"],
      ["Nolan", "Morris"], ["Christian", "Morales"], ["Aaron", "Murphy"], ["Cameron", "Cook"],
      ["Ezekiel", "Rogers"], ["Colton", "Gutierrez"], ["Luca", "Ortiz"], ["Landon", "Morgan"],
      ["Hunter", "Cooper"], ["Jonathan", "Peterson"], ["Santiago", "Bailey"], ["Axel", "Reed"],
      ["Easton", "Kelly"], ["Cooper", "Howard"], ["Jeremiah", "Ramos"], ["Angel", "Kim"],
      ["Roman", "Cox"], ["Connor", "Ward"], ["Jameson", "Richardson"], ["Robert", "Watson"],
      ["Everett", "Brooks"], ["Jordan", "Chavez"], ["Nicholas", "Wood"], ["Dominic", "James"],
      ["Austin", "Bennett"], ["Ian", "Gray"], ["Adam", "Mendoza"], ["Carson", "Ruiz"],
      ["Jaxson", "Hughes"], ["Kai", "Price"], ["Xavier", "Alvarez"], ["Jace", "Castillo"],
      ["Bentley", "Sanders"], ["Leonardo", "Patel"], ["Wesley", "Myers"], ["Kayden", "Long"],
      ["Brody", "Ross"], ["Silas", "Foster"], ["Bennett", "Jimenez"], ["Zayden", "Powell"],
      ["Ryder", "Jenkins"], ["Jason", "Perry"], ["Declan", "Russell"], ["Brandon", "Sullivan"],
      ["Evan", "Ford"], ["Parker", "Hamilton"], ["Rowan", "Graham"], ["Micah", "Wallace"]
    ]
  },
  Spanish: {
    female: [
      ["Sofía", "García"], ["Valentina", "Rodriguez"], ["Isabella", "González"], ["Camila", "Fernández"],
      ["Valeria", "López"], ["Mariana", "Martínez"], ["Gabriela", "Sánchez"], ["Daniela", "Pérez"],
      ["María José", "Gómez"], ["Victoria", "Martin"], ["Martina", "Jiménez"], ["Lucía", "Ruiz"],
      ["Ximena", "Hernández"], ["Sara", "Díaz"], ["Samantha", "Moreno"], ["Julia", "Muñoz"],
      ["Regina", "Álvarez"], ["Renata", "Romero"], ["Alejandra", "Alonso"], ["Natalia", "Gutiérrez"],
      ["Elena", "Navarro"], ["Adriana", "Torres"], ["Catalina", "Domínguez"], ["Paula", "Vázquez"],
      ["Abril", "Ramos"], ["Agustina", "Gil"], ["Antonia", "Ramírez"], ["Constanza", "Serrano"],
      ["Emilia", "Blanco"], ["Fabiana", "Molina"], ["Guadalupe", "Morales"], ["Julieta", "Ortega"],
      ["Lorena", "Delgado"], ["Micaela", "Castro"], ["Pilar", "Ortiz"], ["Salomé", "Rubio"],
      ["Verónica", "Marín"], ["Alma", "Sanz"], ["Amelia", "Iglesias"], ["Aitana", "Nuñez"],
      ["Clara", "Medina"], ["Elisa", "Garrido"], ["Esther", "Santos"], ["Florencia", "Castillo"],
      ["Giselle", "Cortés"], ["Helena", "Lozano"], ["Irene", "Guerrero"], ["Jimena", "Cano"],
      ["Lara", "Prieto"], ["Leire", "Méndez"], ["Lidia", "Cruz"], ["Lola", "Gallego"],
      ["Malena", "Vega"], ["Manuela", "Herrera"], ["Noa", "Peña"], ["Olivia", "León"],
      ["Rocío", "Cabrera"], ["Triana", "Calvo"], ["Zoe", "Vidal"], ["Ariadna", "Flores"],
      ["Blanca", "Campos"], ["Candela", "Vega"], ["Carmen", "Fuentes"], ["Cecilia", "Soler"],
      ["Diana", "Reyes"], ["Fátima", "De la Cruz"], ["Inés", "Diez"], ["Laia", "Pascual"],
      ["Laura", "Ibañez"], ["Lina", "Esteban"], ["Luisa", "Giménez"], ["Marta", "Aguilar"],
      ["Mía", "Ferrer"], ["Nerea", "Soria"], ["Nora", "Vicente"], ["Patricia", "Benítez"],
      ["Raquel", "Camacho"], ["Silvia", "Arias"], ["Teresa", "Mora"], ["Valeria", "Carmona"],
      ["Violeta", "Sáez"], ["Aina", "Gallardo"], ["Alba", "Rojas"], ["Alicia", "Bravo"],
      ["Amanda", "Soto"], ["Ana", "Izquierdo"], ["Andrea", "Pardo"], ["Carla", "Merino"],
      ["Carolina", "Crespo"], ["Claudia", "Román"], ["Cristina", "Redondo"], ["Daniela", "Gallego"],
      ["Emma", "Marcos"], ["Eva", "Lorenzo"], ["Gabriela", "Abad"], ["India", "Jurado"],
      ["Jana", "Bueno"], ["Júlia", "Navas"], ["Laila", "Quintana"], ["Lola", "Acosta"],
      ["Mar", "Escobar"], ["Marina", "Del Río"], ["Noelia", "Herrero"], ["Nuria", "Montero"],
      ["Rebeca", "Sierra"], ["Sandra", "Ponce"], ["Sara", "Rey"], ["Sofía", "Varela"],
      ["Valeria", "Velasco"], ["Vega", "Roldán"], ["Yara", "Amador"], ["Zaira", "Plaza"]
    ],
    male: [
      ["Santiago", "García"], ["Mateo", "Rodriguez"], ["Sebastián", "González"], ["Leonardo", "Fernández"],
      ["Matías", "López"], ["Emiliano", "Martínez"], ["Diego", "Sánchez"], ["Miguel Ángel", "Pérez"],
      ["Alejandro", "Gómez"], ["Daniel", "Martin"], ["Joaquín", "Jiménez"], ["Samuel", "Ruiz"],
      ["Lucas", "Hernández"], ["Benjamín", "Díaz"], ["Thiago", "Moreno"], ["Nicolás", "Muñoz"],
      ["Adrián", "Álvarez"], ["Ángel", "Romero"], ["Bautista", "Alonso"], ["Carlos", "Gutiérrez"],
      ["David", "Navarro"], ["Emmanuel", "Torres"], ["Felipe", "Domínguez"], ["Gabriel", "Vázquez"],
      ["Hugo", "Ramos"], ["Ignacio", "Gil"], ["Javier", "Ramírez"], ["Kevin", "Serrano"],
      ["Lorenzo", "Blanco"], ["Marcos", "Molina"], ["Noah", "Morales"], ["Óscar", "Ortega"],
      ["Pablo", "Delgado"], ["Rafael", "Castro"], ["Simón", "Ortiz"], ["Tomás", "Rubio"],
      ["Valentín", "Marín"], ["Aarón", "Sanz"], ["Abel", "Iglesias"], ["Agustín", "Nuñez"],
      ["Alberto", "Medina"], ["Alonso", "Garrido"], ["Álvaro", "Santos"], ["Antonio", "Castillo"],
      ["Arturo", "Cortés"], ["Bruno", "Lozano"], ["César", "Guerrero"], ["Cristian", "Cano"],
      ["Damián", "Prieto"], ["Darío", "Méndez"], ["Eduardo", "Cruz"], ["Enzo", "Gallego"],
      ["Eric", "Vega"], ["Esteban", "Herrera"], ["Fabio", "Peña"], ["Fausto", "León"],
      ["Fernando", "Cabrera"], ["Francisco", "Calvo"], ["Gerardo", "Vidal"], ["Germán", "Flores"],
      ["Gonzalo", "Campos"], ["Gregorio", "Vega"], ["Guillermo", "Fuentes"], ["Héctor", "Soler"],
      ["Hernán", "Reyes"], ["Horacio", "De la Cruz"], ["Iker", "Diez"], ["Ismael", "Pascual"],
      ["Iván", "Ibañez"], ["Jaime", "Esteban"], ["Jesús", "Giménez"], ["Joel", "Aguilar"],
      ["Jonás", "Ferrer"], ["Jorge", "Soria"], ["José", "Vicente"], ["Juan", "Benítez"],
      ["Julián", "Camacho"], ["Leo", "Arias"], ["Lino", "Mora"], ["Lisandro", "Carmona"],
      ["Luciano", "Sáez"], ["Manuel", "Gallardo"], ["Mariano", "Rojas"], ["Martín", "Bravo"],
      ["Mauro", "Soto"], ["Máximo", "Izquierdo"], ["Milo", "Pardo"], ["Octavio", "Merino"],
      ["Patricio", "Crespo"], ["Pedro", "Román"], ["Raúl", "Redondo"], ["Ricardo", "Gallego"],
      ["Roberto", "Marcos"], ["Rodrigo", "Lorenzo"], ["Rubén", "Abad"], ["Salvador", "Jurado"],
      ["Saúl", "Bueno"], ["Sergio", "Navas"], ["Silvestre", "Quintana"], ["Teo", "Acosta"],
      ["Tristán", "Escobar"], ["Ulises", "Del Río"], ["Vicente", "Herrero"], ["Víctor", "Montero"]
    ]
  },
  French: {
    female: [
      ["Emma", "Martin"], ["Jade", "Bernard"], ["Louise", "Thomas"], ["Alice", "Petit"],
      ["Chloé", "Robert"], ["Lina", "Richard"], ["Rose", "Durand"], ["Léa", "Dubois"],
      ["Anna", "Moreau"], ["Mila", "Laurent"], ["Ambre", "Simon"], ["Julia", "Michel"],
      ["Inès", "Lefebvre"], ["Mia", "Leroy"], ["Léna", "Roux"], ["Juliette", "David"],
      ["Agathe", "Bertrand"], ["Lou", "Morel"], ["Clara", "Fournier"], ["Jeanne", "Girard"],
      ["Manon", "Bonnet"], ["Eva", "Dupont"], ["Camille", "Lambert"], ["Zoé", "Fontaine"],
      ["Lola", "Rousseau"], ["Charlotte", "Vincent"], ["Sarah", "Muller"], ["Lucie", "Lefevre"],
      ["Adèle", "Faure"], ["Margaux", "Andre"], ["Olivia", "Mercier"], ["Victoria", "Blanc"],
      ["Romane", "Guerin"], ["Iris", "Boyer"], ["Sofia", "Garnier"], ["Augustine", "Chevalier"],
      ["Romy", "Francois"], ["Elena", "Legrand"], ["Alix", "Gauthier"], ["Capucine", "Garcia"],
      ["Victoire", "Perrin"], ["Gabrielle", "Robin"], ["Margot", "Clement"], ["Mathilde", "Morin"],
      ["Noémie", "Nicolas"], ["Théa", "Henry"], ["Céleste", "Roussel"], ["Nina", "Mathieu"],
      ["Roxane", "Gautier"], ["Éléonore", "Masson"], ["Lise", "Marchand"], ["Valentine", "Duval"],
      ["Apolline", "Denis"], ["Joséphine", "Dumont"], ["Luce", "Marie"], ["Olympe", "Lemaire"],
      ["Suzanne", "Noel"], ["Alma", "Meyer"], ["Charlie", "Dufour"], ["Diane", "Meunier"],
      ["Faustine", "Brun"], ["Héloïse", "Blanchard"], ["Madeleine", "Giraud"], ["Salomé", "Joly"],
      ["Thaïs", "Riviere"], ["Yasmine", "Lucas"], ["Zélie", "Brunet"], ["Anouk", "Gaillard"],
      ["Bérénice", "Barbier"], ["Constance", "Arnaud"], ["Daphné", "Martinez"], ["Esmée", "Gerard"],
      ["Félicie", "Roche"], ["Garance", "Renard"], ["Hermine", "Schmitt"], ["Isilde", "Leroux"],
      ["Lison", "Colin"], ["Mélodie", "Pons"], ["Naëlle", "Barre"], ["Ombeline", "Leclercq"],
      ["Pénélope", "Picard"], ["Quitterie", "Aubert"], ["Soline", "Royer"], ["Toscane", "Leconte"],
      ["Violette", "Leclerc"], ["Aliénor", "Hubert"], ["Ariane", "Caron"], ["Blanche", "Germain"],
      ["Célia", "Dupuy"], ["Élise", "Roy"], ["Florine", "Deschamps"], ["Gayané", "Guillot"],
      ["Honorine", "Bailly"], ["Iseult", "Jean"], ["Jasmine", "Petitjean"], ["Léonie", "Renaud"],
      ["Marilou", "Poirier"], ["Nine", "Lejeune"], ["Océane", "Vidal"], ["Paloma", "Bourgeois"],
      ["Prune", "Berger"], ["Raphaëlle", "Lemoine"], ["Sixtine", "Philippe"], ["Thérèse", "Lacroix"],
      ["Ursule", "Guérin"], ["Victorine", "Girault"], ["Wendy", "Poulain"], ["Xavière", "Maillet"],
      ["Ysaline", "Breton"], ["Zita", "Guyot"], ["Anaëlle", "Hamon"], ["Castille", "Jacob"]
    ],
    male: [
      ["Gabriel", "Martin"], ["Léo", "Bernard"], ["Raphaël", "Thomas"], ["Arthur", "Petit"],
      ["Louis", "Robert"], ["Jules", "Richard"], ["Adam", "Durand"], ["Maël", "Dubois"],
      ["Lucas", "Moreau"], ["Hugo", "Laurent"], ["Noah", "Simon"], ["Gabin", "Michel"],
      ["Liam", "Lefebvre"], ["Sacha", "Leroy"], ["Paul", "Roux"], ["Aaron", "David"],
      ["Mohamed", "Bertrand"], ["Ethan", "Morel"], ["Isaac", "Fournier"], ["Tom", "Girard"],
      ["Victor", "Bonnet"], ["Timéo", "Dupont"], ["Enzo", "Lambert"], ["Axel", "Fontaine"],
      ["Antoine", "Rousseau"], ["Léon", "Vincent"], ["Valentin", "Muller"], ["Clément", "Lefevre"],
      ["Maxence", "Faure"], ["Baptiste", "Andre"], ["Martin", "Mercier"], ["Yanis", "Blanc"],
      ["Noé", "Guerin"], ["Tiago", "Boyer"], ["Théo", "Garnier"], ["Marius", "Chevalier"],
      ["Nolan", "Francois"], ["Mathis", "Legrand"], ["Rayan", "Gauthier"], ["Eliott", "Garcia"],
      ["Augustin", "Perrin"], ["Amir", "Robin"], ["Kylian", "Clement"], ["Côme", "Morin"],
      ["Marceau", "Nicolas"], ["Milo", "Henry"], ["Naël", "Roussel"], ["Soan", "Mathieu"],
      ["Owen", "Gautier"], ["Simon", "Masson"], ["Tristan", "Marchand"], ["Alexis", "Duval"],
      ["Camille", "Denis"], ["Émile", "Dumont"], ["Gaspard", "Marie"], ["Malo", "Lemaire"],
      ["Nino", "Noel"], ["Robin", "Meyer"], ["Samuel", "Dufour"], ["Antonin", "Meunier"],
      ["Bastien", "Brun"], ["Corentin", "Blanchard"], ["Dorian", "Giraud"], ["Félix", "Joly"],
      ["Grégoire", "Riviere"], ["Hector", "Lucas"], ["Ilan", "Brunet"], ["Jean", "Gaillard"],
      ["Kenzo", "Barbier"], ["Léandre", "Arnaud"], ["Matthieu", "Martinez"], ["Oscar", "Gerard"],
      ["Pierre", "Roche"], ["Quentin", "Renard"], ["Rémi", "Schmitt"], ["Swann", "Leroux"],
      ["Thibault", "Colin"], ["Ulysse", "Pons"], ["Vianney", "Barre"], ["William", "Leclercq"],
      ["Xavier", "Picard"], ["Yann", "Aubert"], ["Zacharie", "Royer"], ["Adrien", "Leconte"],
      ["Alban", "Leclerc"], ["Alexandre", "Hubert"], ["Anatole", "Caron"], ["Aurèle", "Germain"],
      ["Benjamin", "Dupuy"], ["César", "Roy"], ["Damien", "Deschamps"], ["Édouard", "Guillot"],
      ["Fabien", "Bailly"], ["Gaël", "Jean"], ["Hadrien", "Petitjean"], ["Ibrahim", "Renaud"],
      ["Jonas", "Poirier"], ["Kevin", "Lejeune"], ["Loïc", "Vidal"], ["Marin", "Bourgeois"],
      ["Nathan", "Berger"], ["Olivier", "Lemoine"], ["Paulin", "Philippe"], ["Roman", "Lacroix"],
      ["Stéphane", "Guérin"], ["Tanguy", "Girault"], ["Urbain", "Poulain"], ["Valère", "Maillet"]
    ]
  },
  German: {
    female: [
      ["Mia", "Müller"], ["Emma", "Schmidt"], ["Sofia", "Schneider"], ["Hannah", "Fischer"],
      ["Emilia", "Weber"], ["Anna", "Meyer"], ["Lina", "Wagner"], ["Mila", "Becker"],
      ["Clara", "Schulz"], ["Lea", "Hoffmann"], ["Lena", "Schäfer"], ["Leonie", "Koch"],
      ["Lilly", "Bauer"], ["Luisa", "Richter"], ["Marie", "Klein"], ["Amelie", "Wolf"],
      ["Sophie", "Schröder"], ["Charlotte", "Neumann"], ["Ida", "Schwarz"], ["Johanna", "Zimmermann"],
      ["Frieda", "Braun"], ["Lara", "Krüger"], ["Mathilda", "Hofmann"], ["Ella", "Hartmann"],
      ["Leni", "Lange"], ["Nele", "Schmitt"], ["Pauline", "Werner"], ["Laura", "Schmitz"],
      ["Sarah", "Krause"], ["Antonia", "Meier"], ["Elisa", "Lehmann"], ["Greta", "Schmid"],
      ["Isabella", "Schulze"], ["Juna", "Maier"], ["Katharina", "Köhler"], ["Maja", "Herrmann"],
      ["Nora", "König"], ["Pia", "Walter"], ["Romy", "Mayer"], ["Selma", "Huber"],
      ["Thea", "Kaiser"], ["Valentina", "Fuchs"], ["Viktoria", "Peters"], ["Zoe", "Lang"],
      ["Alina", "Scholz"], ["Carla", "Möller"], ["Elif", "Weiß"], ["Fiona", "Jung"],
      ["Hailey", "Hahn"], ["Ina", "Schubert"], ["Jara", "Vogel"], ["Kira", "Friedrich"],
      ["Lia", "Keller"], ["Mara", "Günther"], ["Nina", "Frank"], ["Olivia", "Berger"],
      ["Paula", "Winkler"], ["Ronja", "Roth"], ["Stella", "Beck"], ["Tabea", "Lorenz"],
      ["Vanessa", "Baumann"], ["Yara", "Franke"], ["Amalia", "Albrecht"], ["Anni", "Schuster"],
      ["Bella", "Simon"], ["Celine", "Ludwig"], ["Diana", "Böhm"], ["Elena", "Winter"],
      ["Fabienne", "Kraus"], ["Gloria", "Martin"], ["Helena", "Schumacher"], ["Jasmin", "Vogt"],
      ["Josephine", "Stein"], ["Jule", "Jäger"], ["Kaja", "Otto"], ["Lilith", "Sommer"],
      ["Lucia", "Groß"], ["Magdalena", "Seidel"], ["Maila", "Heinrich"], ["Marla", "Brandt"],
      ["Miriam", "Haas"], ["Nala", "Schreiber"], ["Paulina", "Graf"], ["Rebecca", "Schulte"],
      ["Sina", "Dietrich"], ["Tamara", "Ziegler"], ["Theresa", "Kühn"], ["Tilda", "Pohl"],
      ["Viola", "Engel"], ["Wibke", "Horn"], ["Xenia", "Busch"], ["Ylvi", "Bergmann"],
      ["Zelda", "Pfeiffer"], ["Aurelia", "Thomas"], ["Bianca", "Voigt"], ["Cosima", "Sauer"],
      ["Daria", "Arnold"], ["Elina", "Wolff"], ["Felicia", "Pohl"], ["Gesa", "Herbst"],
      ["Henriette", "Kruse"], ["Isabell", "Renner"], ["Jana", "Jansen"], ["Joana", "Barth"],
      ["Jolanda", "Linke"], ["Karla", "Lutz"], ["Laila", "Steiner"], ["Linda", "Gebhardt"],
      ["Lisbeth", "Rau"], ["Lorena", "Schenk"], ["Malina", "Stark"], ["Maxi", "Thiel"]
    ],
    male: [
      ["Noah", "Müller"], ["Ben", "Schmidt"], ["Paul", "Schneider"], ["Leon", "Fischer"],
      ["Jonas", "Weber"], ["Finn", "Meyer"], ["Elias", "Wagner"], ["Felix", "Becker"],
      ["Luis", "Schulz"], ["Lukas", "Hoffmann"], ["Maximilian", "Schäfer"], ["Luca", "Koch"],
      ["Henry", "Bauer"], ["Max", "Richter"], ["Oskar", "Klein"], ["Emil", "Wolf"],
      ["Anton", "Schröder"], ["Jakob", "Neumann"], ["Theo", "Schwarz"], ["Matteo", "Zimmermann"],
      ["Liam", "Braun"], ["Moritz", "Krüger"], ["Leo", "Hofmann"], ["David", "Hartmann"],
      ["Julian", "Lange"], ["Hannes", "Schmitt"], ["Karl", "Werner"], ["Erik", "Schmitz"],
      ["Johann", "Krause"], ["Mats", "Meier"], ["Tom", "Lehmann"], ["Valentin", "Schmid"],
      ["Alexander", "Schulze"], ["Linus", "Maier"], ["Niklas", "Köhler"], ["Simon", "Herrmann"],
      ["Philipp", "König"], ["Jan", "Walter"], ["Till", "Mayer"], ["Vincent", "Huber"],
      ["Samuel", "Kaiser"], ["Jonathan", "Fuchs"], ["Rafael", "Peters"], ["Levi", "Lang"],
      ["Fabian", "Scholz"], ["Florian", "Möller"], ["Mika", "Weiß"], ["Adrian", "Jung"],
      ["Jannik", "Hahn"], ["Lennard", "Schubert"], ["Arthur", "Vogel"], ["Bruno", "Friedrich"],
      ["Constantin", "Keller"], ["Dominik", "Günther"], ["Franz", "Frank"], ["Gustav", "Berger"],
      ["Justus", "Winkler"], ["Kilian", "Roth"], ["Levin", "Beck"], ["Malte", "Lorenz"],
      ["Nico", "Baumann"], ["Patrick", "Franke"], ["Quentin", "Albrecht"], ["Richard", "Schuster"],
      ["Sebastian", "Simon"], ["Timon", "Ludwig"], ["Tristan", "Böhm"], ["Victor", "Winter"],
      ["Aaron", "Kraus"], ["Benedikt", "Martin"], ["Carl", "Schumacher"], ["Daniel", "Vogt"],
      ["Frederik", "Stein"], ["Gregor", "Jäger"], ["Hugo", "Otto"], ["Ilias", "Sommer"],
      ["Jaron", "Groß"], ["Konrad", "Seidel"], ["Laurenz", "Heinrich"], ["Marlon", "Brandt"],
      ["Nikolai", "Haas"], ["Ole", "Schreiber"], ["Peter", "Graf"], ["Rasmus", "Schulte"],
      ["Silas", "Dietrich"], ["Thies", "Ziegler"], ["Ulrich", "Kühn"], ["Willem", "Pohl"],
      ["Xaver", "Engel"], ["Yuri", "Horn"], ["Zacharias", "Busch"], ["Adam", "Bergmann"],
      ["Bela", "Pfeiffer"], ["Christoph", "Thomas"], ["Darian", "Voigt"], ["Eduard", "Sauer"],
      ["Ferdinand", "Arnold"], ["Gideon", "Wolff"], ["Henning", "Pohl"], ["Ivo", "Herbst"],
      ["Jasper", "Kruse"], ["Korbinian", "Renner"], ["Leander", "Jansen"], ["Magnus", "Barth"],
      ["Nepomuk", "Linke"], ["Otis", "Lutz"], ["Peer", "Steiner"], ["Ruben", "Gebhardt"]
    ]
  },
  Italian: {
    female: [
      ["Sofia", "Rossi"], ["Giulia", "Russo"], ["Aurora", "Ferrari"], ["Alice", "Esposito"],
      ["Ginevra", "Bianchi"], ["Emma", "Romano"], ["Giorgia", "Colombo"], ["Beatrice", "Ricci"],
      ["Greta", "Marino"], ["Vittoria", "Greco"], ["Anna", "Bruno"], ["Matilde", "Gallo"],
      ["Chiara", "Conti"], ["Camilla", "De Luca"], ["Ludovica", "Mancini"], ["Martina", "Costa"],
      ["Sara", "Giordano"], ["Nicole", "Rizzo"], ["Gaia", "Lombardi"], ["Elisa", "Moretti"],
      ["Isabel", "Barbieri"], ["Adele", "Fontana"], ["Bianca", "Santoro"], ["Viola", "Mariani"],
      ["Azzurra", "Rinaldi"], ["Caterina", "Caruso"], ["Cecilia", "Ferrara"], ["Diana", "Galli"],
      ["Elena", "Leone"], ["Emily", "Longo"], ["Francesca", "Gentile"], ["Gioia", "Serra"],
      ["Irene", "Coppola"], ["Margherita", "De Santis"], ["Mia", "D'Amico"], ["Noemi", "Marchetti"],
      ["Rebecca", "Martini"], ["Ambra", "Grassi"], ["Anita", "Pellegrini"], ["Arianna", "Farina"],
      ["Asia", "Villa"], ["Carlotta", "Conte"], ["Chloe", "Ferri"], ["Clarissa", "Rossetti"],
      ["Corinne", "Bernardi"], ["Dafne", "Amato"], ["Diletta", "Bellini"], ["Elettra", "Cattaneo"],
      ["Eva", "Piras"], ["Federica", "Parisi"], ["Felicia", "Barone"], ["Fiamma", "Monti"],
      ["Flora", "Fabbri"], ["Gilda", "Pagano"], ["Gisele", "Vitale"], ["Gisella", "Morelli"],
      ["Ilaria", "Messina"], ["Iris", "Testa"], ["Isabella", "Sanna"], ["Jasmine", "Negri"],
      ["Jessica", "Valentini"], ["Jolanda", "Donati"], ["Lara", "Basile"], ["Laura", "Palmieri"],
      ["Lavinia", "Cozzi"], ["Lea", "Sartori"], ["Luce", "Riva"], ["Lucrezia", "Battaglia"],
      ["Luna", "Silvestri"], ["Maddalena", "Pugliese"], ["Maria", "Caputo"], ["Marina", "Fiorillo"],
      ["Maya", "Sala"], ["Melissa", "Piras"], ["Miriam", "Lombardo"], ["Nadia", "Benedetti"],
      ["Nina", "Carli"], ["Olivia", "Piazza"], ["Pamela", "Gatti"], ["Paola", "Pellegrino"],
      ["Penelope", "Marini"], ["Perla", "Pinto"], ["Prisca", "Furlan"], ["Rachele", "Damico"],
      ["Raissa", "Lupo"], ["Renata", "Ferrero"], ["Rita", "Mazza"], ["Rosa", "Clementi"],
      ["Sabrina", "Gobbo"], ["Samira", "Orlando"], ["Serena", "Corsi"], ["Sharon", "Bianco"],
      ["Silvia", "Poli"], ["Sole", "Grossi"], ["Stella", "Mancuso"], ["Susanna", "Ferrante"],
      ["Sveva", "Rinaldi"], ["Talita", "De Angelis"], ["Tamara", "Guerra"], ["Tea", "Pace"],
      ["Teresa", "D'Angelo"], ["Valentina", "Sorrentino"], ["Valeria", "Galli"], ["Vanessa", "Carboni"],      ["Vera", "Basso"], ["Veronica", "Lorusso"], ["Viola", "Fiore"], ["Virginia", "Tripodi"],
      ["Viviana", "Moro"], ["Zoe", "Negri"], ["Agnese", "Palumbo"], ["Alessandra", "Marra"]
    ],
    male: [
      ["Leonardo", "Rossi"], ["Francesco", "Russo"], ["Alessandro", "Ferrari"], ["Lorenzo", "Esposito"],
      ["Mattia", "Bianchi"], ["Andrea", "Romano"], ["Gabriele", "Colombo"], ["Riccardo", "Ricci"],
      ["Tommaso", "Marino"], ["Edoardo", "Greco"], ["Diego", "Bruno"], ["Matteo", "Gallo"],
      ["Samuele", "Conti"], ["Nicolò", "De Luca"], ["Antonio", "Mancini"], ["Federico", "Costa"],
      ["Giuseppe", "Giordano"], ["Giovanni", "Rizzo"], ["Pietro", "Lombardi"], ["Filippo", "Moretti"],
      ["Davide", "Barbieri"], ["Cristian", "Fontana"], ["Michele", "Santoro"], ["Elia", "Mariani"],
      ["Christian", "Rinaldi"], ["Gabriel", "Caruso"], ["Marco", "Ferrara"], ["Jacopo", "Galli"],
      ["Raffaele", "Leone"], ["Salvatore", "Longo"], ["Simone", "Gentile"], ["Vincenzo", "Serra"],
      ["Alessio", "Coppola"], ["Daniele", "De Santis"], ["Enea", "D'Amico"], ["Noah", "Marchetti"],
      ["Thomas", "Martini"], ["Brando", "Grassi"], ["Carmine", "Pellegrini"], ["Cesare", "Farina"],
      ["Claudio", "Villa"], ["Dario", "Conte"], ["Denis", "Ferri"], ["Domenico", "Rossetti"],
      ["Emanuele", "Bernardi"], ["Enrico", "Amato"], ["Ettore", "Bellini"], ["Fabio", "Cattaneo"],
      ["Flavio", "Piras"], ["Gaetano", "Parisi"], ["Giacomo", "Barone"], ["Gioele", "Monti"],
      ["Giorgio", "Fabbri"], ["Giulio", "Pagano"], ["Ivan", "Vitale"], ["Leone", "Morelli"],
      ["Liam", "Messina"], ["Manuel", "Testa"], ["Massimo", "Sanna"], ["Mauro", "Negri"],
      ["Mirko", "Valentini"], ["Neri", "Donati"], ["Nicola", "Basile"], ["Omar", "Palmieri"],
      ["Paolo", "Cozzi"], ["Patrick", "Sartori"], ["Raoul", "Riva"], ["Rosario", "Battaglia"],
      ["Ryan", "Silvestri"], ["Santiago", "Pugliese"], ["Sergio", "Caputo"], ["Stefano", "Fiorillo"],
      ["Tancredi", "Sala"], ["Tiziano", "Piras"], ["Umberto", "Lombardo"], ["Valerio", "Benedetti"],
      ["Vasco", "Carli"], ["Walter", "Piazza"], ["Zeno", "Gatti"], ["Achille", "Pellegrino"],
      ["Adriano", "Marini"], ["Alberto", "Pinto"], ["Aldo", "Furlan"], ["Alfredo", "Damico"],
      ["Amedeo", "Lupo"], ["Angelo", "Ferrero"], ["Armando", "Mazza"], ["Arturo", "Clementi"],
      ["Augusto", "Gobbo"], ["Aurelio", "Orlando"], ["Baldassarre", "Corsi"], ["Bartolomeo", "Bianco"],
      ["Beniamino", "Poli"], ["Bernardo", "Grossi"], ["Biagio", "Mancuso"], ["Calogero", "Ferrante"],
      ["Carlo", "Rinaldi"], ["Casimiro", "De Angelis"], ["Celestino", "Guerra"], ["Ciro", "Pace"],
      ["Cosimo", "D'Angelo"], ["Costantino", "Sorrentino"], ["Damiano", "Galli"], ["Danilo", "Carboni"],
      ["Demis", "Basso"], ["Dino", "Lorusso"], ["Donato", "Fiore"], ["Duccio", "Tripodi"]
    ]
  },
  Japanese: {
    female: [
      ["佐藤", "陽葵"], ["鈴木", "凛"], ["高橋", "詩"], ["田中", "結菜"], ["伊藤", "咲良"],
      ["渡辺", "莉子"], ["山本", "陽菜"], ["中村", "芽依"], ["小林", "愛奈"], ["加藤", "結愛"],
      ["吉田", "心春"], ["山田", "杏"], ["佐々木", "美咲"], ["山口", "葵"], ["松本", "愛莉"],
      ["井上", "楓"], ["木村", "優奈"], ["林", "ひなた"], ["清水", "桜"], ["山崎", "莉緒"],
      ["森", "結衣"], ["阿部", "朱莉"], ["池田", "美桜"], ["橋本", "紬"], ["石川", "澪"],
      ["山下", "琴音"], ["中島", "凛花"], ["前田", "柚葉"], ["藤田", "彩葉"], ["小川", "恵麻"],
      ["岡田", "百花"], ["後藤", "愛梨"], ["長谷川", "日和"], ["村上", "栞奈"], ["近藤", "花"],
      ["石井", "乃愛"], ["斎藤", "真央"], ["坂本", "美月"], ["遠藤", "千尋"], ["藤井", "玲奈"],
      ["青木", "沙耶"], ["西村", "穂乃花"], ["福田", "奈々"], ["太田", "一華"], ["三浦", "璃子"],
      ["藤原", "菜月"], ["岡本", "優衣"], ["松田", "小春"], ["中川", "結月"], ["中野", "杏奈"],
      ["原田", "紗奈"], ["小野", "美緒"], ["田村", "朱音"], ["竹内", "咲希"], ["金子", "陽葵"],
      ["和田", "悠月"], ["中山", "彩乃"], ["石田", "美羽"], ["上田", "莉央"], ["森田", "愛華"],
      ["原", "優月"], ["柴田", "楓花"], ["宮崎", "咲良"], ["酒井", "美優"], ["工藤", "詩織"],
      ["横山", "瑠菜"], ["宮本", "莉奈"], ["内藤", "愛菜"], ["安藤", "結菜"], ["島田", "百々果"],
      ["谷口", "心結"], ["大西", "柚希"], ["今井", "絢音"], ["丸山", "咲良"], ["菊地", "日菜"],
      ["野口", "陽菜"], ["久保", "莉緒"], ["佐野", "心陽"], ["千葉", "優花"], ["川崎", "愛莉"],
      ["岩崎", "美咲"], ["古川", "葵"], ["野村", "結愛"], ["新井", "芽生"], ["桜井", "心春"],
      ["高田", "杏"], ["大塚", "ひかり"], ["平野", "楓"], ["杉山", "優奈"], ["村田", "ひなた"],
      ["増田", "桜"], ["小島", "莉緒"], ["河野", "結衣"], ["清水", "朱莉"], ["上野", "美桜"],
      ["武田", "紬"], ["松井", "澪"], ["市川", "琴音"], ["小山", "凛花"], ["大野", "柚葉"],
      ["飯田", "彩葉"], ["木下", "恵麻"], ["佐藤", "百花"], ["鈴木", "愛梨"], ["高橋", "日和"],
      ["田中", "栞奈"], ["伊藤", "花"], ["渡辺", "乃愛"], ["山本", "真央"], ["中村", "美月"],
      ["小林", "千尋"], ["加藤", "玲奈"], ["吉田", "穂乃花"], ["山田", "奈々"], ["佐々木", "一華"]
    ],
    male: [
      ["佐藤", "蓮"], ["鈴木", "陽翔"], ["高橋", "蒼"], ["田中", "湊"], ["伊藤", "樹"],
      ["渡辺", "悠真"], ["山本", "大和"], ["中村", "陽太"], ["小林", "律"], ["加藤", "朝陽"],
      ["吉田", "颯"], ["山田", "新"], ["佐々木", "伊織"], ["山口", "大輝"], ["松本", "碧"],
      ["井上", "悠"], ["木村", "暖"], ["林", "蒼大"], ["清水", "陸"], ["山崎", "健太"],
      ["森", "颯真"], ["阿部", "翔"], ["池田", "結翔"], ["橋本", "瑛太"], ["石川", "湊斗"],
      ["山下", "晴"], ["中島", "一颯"], ["前田", "悠人"], ["藤田", "陽仁"], ["小川", "奏太"],
      ["岡田", "丈"], ["後藤", "蒼真"], ["長谷川", "凛"], ["村上", "海斗"], ["近藤", "蓮"],
      ["石井", "悠斗"], ["斎藤", "旭"], ["坂本", "瑛斗"], ["遠藤", "龍之介"], ["藤井", "駿"],
      ["青木", "拓真"], ["西村", "大翔"], ["福田", "湊翔"], ["太田", "陽"], ["三浦", "朔"],
      ["藤原", "蒼空"], ["岡本", "隼人"], ["松田", "漣"], ["中川", "奏多"], ["中野", "結人"],
      ["原田", "陸斗"], ["小野", "翔太"], ["田村", "晴翔"], ["竹内", "悠"], ["金子", "楓"],
      ["和田", "壮"], ["中山", "陽"], ["石田", "琉生"], ["上田", "遥"], ["森田", "大智"],
      ["原", "颯太"], ["柴田", "健"], ["宮崎", "拓海"], ["酒井", "亮"], ["工藤", "輝"],
      ["横山", "悠生"], ["宮本", "和真"], ["内藤", "優"], ["安藤", "誠"], ["島田", "純"],
      ["谷口", "啓"], ["大西", "翔"], ["今井", "翼"], ["丸山", "雅"], ["菊地", "直樹"],
      ["野口", "光"], ["久保", "哲也"], ["佐野", "徹"], ["千葉", "浩"], ["川崎", "学"],
      ["岩崎", "聡"], ["古川", "博"], ["野村", "明"], ["新井", "剛"], ["桜井", "雄"],
      ["高田", "勇"], ["大塚", "修"], ["平野", "豊"], ["杉山", "信"], ["村田", "淳"],
      ["増田", "茂"], ["小島", "弘"], ["河野", "孝"], ["清水", "昭"], ["上野", "正"],
      ["武田", "清"], ["松井", "進"], ["市川", "忠"], ["小山", "義"], ["大野", "晃"],
      ["飯田", "良"], ["木下", "紀"], ["佐藤", "秀"], ["鈴木", "久"], ["高橋", "康"],
      ["田中", "英"], ["伊藤", "文"], ["渡辺", "武"], ["山本", "幸"], ["中村", "邦"]
    ]
  },
  Chinese: {
    female: [
      ["王", "芳华"], ["李", "静雅"], ["张", "欣怡"], ["刘", "雨桐"], ["陈", "诗涵"],
      ["杨", "梦洁"], ["赵", "雅琳"], ["黄", "紫萱"], ["周", "思妤"], ["吴", "晓月"],
      ["徐", "佳琪"], ["孙", "美玲"], ["胡", "婉婷"], ["朱", "雪芬"], ["高", "瑞雪"],
      ["林", "晓燕"], ["何", "思佳"], ["郭", "欣妍"], ["罗", "晨曦"], ["宋", "子涵"],
      ["郑", "一诺"], ["谢", "雨薇"], ["唐", "婧琪"], ["韩", "乐瑶"], ["曹", "梦琪"],
      ["许", "可馨"], ["邓", "思颖"], ["萧", "语嫣"], ["冯", "芷若"], ["程", "依娜"],
      ["蔡", "海琳"], ["丁", "晓慧"], ["沈", "文静"], ["潘", "月婵"], ["田", "安琪"],
      ["杜", "佳妮"], ["姜", "晓萱"], ["范", "诗琪"], ["苏", "晓萌"], ["叶", "欣悦"],
      ["吕", "雅静"], ["魏", "晴朗"], ["孟", "思彤"], ["蒋", "佳怡"], ["阎", "美君"],
      ["余", "晓丽"], ["袁", "静香"], ["任", "雅楠"], ["姚", "梦露"], ["傅", "晓涵"],
      ["薛", "若瑄"], ["陶", "佳颖"], ["顾", "诗雅"], ["方", "雨婷"], ["崔", "晓琳"],
      ["石", "梦瑶"], ["白", "婉儿"], ["段", "欣然"], ["秦", "语彤"], ["邵", "思涵"],
      ["龚", "雅雯"], ["侯", "静蕾"], ["尹", "晓菲"], ["常", "心悦"], ["江", "佳慧"],
      ["夏", "雨欣"], ["龙", "晓彤"], ["戴", "安妮"], ["万", "诗雨"], ["卢", "梦洁"],
      ["廖", "雅琪"], ["金", "晓晨"], ["毛", "思琪"], ["贺", "婉如"], ["赖", "欣怡"],
      ["钱", "雨涵"], ["路", "晓曼"], ["易", "佳雪"], ["庞", "晓静"], ["康", "美琳"],
      ["汤", "欣妍"], ["牛", "雅静"], ["温", "晓菲"], ["花", "雨桐"], ["雷", "梦瑶"],
      ["安", "诗涵"], ["章", "静香"], ["史", "晓月"], ["葛", "婉婷"], ["文", "欣悦"],
      ["王", "佳慧"], ["李", "晨曦"], ["张", "晓萱"], ["刘", "紫萱"], ["陈", "梦洁"],
      ["杨", "欣怡"], ["赵", "雨桐"], ["黄", "诗涵"], ["周", "雅琳"], ["吴", "思妤"],
      ["徐", "晓月"], ["孙", "佳琪"], ["胡", "美玲"], ["朱", "婉婷"], ["高", "雪芬"],
      ["林", "瑞雪"], ["何", "晓燕"], ["郭", "思佳"], ["罗", "欣妍"], ["宋", "晨曦"],
      ["郑", "子涵"], ["谢", "一诺"], ["唐", "雨薇"], ["韩", "婧琪"], ["曹", "乐瑶"],
      ["许", "梦琪"], ["邓", "可馨"], ["萧", "思颖"], ["冯", "语嫣"], ["程", "芷若"],
      ["蔡", "依娜"], ["丁", "海琳"], ["沈", "晓慧"], ["潘", "文静"], ["田", "月婵"]
    ],
    male: [
      ["李", "伟诚"], ["王", "浩然"], ["张", "博文"], ["刘", "子轩"], ["陈", "宇航"],
      ["杨", "俊熙"], ["赵", "皓轩"], ["黄", "文杰"], ["周", "博涛"], ["吴", "嘉豪"],
      ["徐", "天佑"], ["孙", "明哲"], ["胡", "致远"], ["朱", "昊天"], ["高", "文昊"],
      ["林", "建华"], ["何", "思源"], ["郭", "俊杰"], ["罗", "志强"], ["宋", "文博"],
      ["郑", "鸿飞"], ["谢", "明轩"], ["唐", "伟祺"], ["韩", "博裕"], ["曹", "国栋"],
      ["许", "瀚文"], ["邓", "俊驰"], ["萧", "天磊"], ["冯", "建宇"], ["程", "志宏"],
      ["蔡", "文彬"], ["丁", "子涵"], ["沈", "俊楠"], ["潘", "明杰"], ["田", "浩宇"],
      ["杜", "文轩"], ["姜", "国强"], ["范", "志明"], ["苏", "俊伟"], ["叶", "博超"],
      ["吕", "明远"], ["魏", "嘉熙"], ["孟", "翰林"], ["蒋", "天翊"], ["阎", "文龙"],
      ["余", "浩铭"], ["袁", "子豪"], ["任", "明辉"], ["姚", "建军"], ["傅", "志伟"],
      ["薛", "嘉诚"], ["陶", "博远"], ["顾", "文涛"], ["方", "俊逸"], ["崔", "国豪"],
      ["石", "明昊"], ["白", "子墨"], ["段", "建辉"], ["秦", "浩然"], ["邵", "文杰"],
      ["龚", "嘉俊"], ["侯", "志刚"], ["尹", "明轩"], ["常", "文昊"], ["江", "建国"],
      ["夏", "俊豪"], ["龙", "志远"], ["戴", "国栋"], ["万", "文博"], ["卢", "子涵"],
      ["廖", "俊杰"], ["金", "明哲"], ["毛", "浩宇"], ["贺", "建华"], ["赖", "博文"],
      ["钱", "宇航"], ["路", "俊熙"], ["易", "皓轩"], ["庞", "文杰"], ["康", "博涛"],
      ["汤", "嘉豪"], ["牛", "天佑"], ["温", "明哲"], ["花", "致远"], ["雷", "昊天"],
      ["安", "文昊"], ["章", "建华"], ["史", "思源"], ["葛", "俊杰"], ["文", "志强"],
      ["王", "文博"], ["李", "鸿飞"], ["张", "明轩"], ["刘", "伟祺"], ["陈", "博裕"],
      ["杨", "国栋"], ["赵", "瀚文"], ["黄", "俊驰"], ["周", "天磊"], ["吴", "建宇"],
      ["徐", "志宏"], ["孙", "文彬"], ["胡", "子涵"], ["朱", "俊楠"], ["高", "明杰"],
      ["林", "浩宇"], ["何", "文轩"], ["郭", "国强"], ["罗", "志明"], ["宋", "俊伟"],
      ["郑", "博超"], ["谢", "明远"], ["唐", "嘉熙"], ["韩", "翰林"], ["曹", "天翊"],
      ["许", "文龙"], ["邓", "浩铭"], ["萧", "子豪"], ["冯", "明辉"], ["程", "志宏"]
    ]
  },
  Korean: {
    female: [
      ["김", "서아"], ["이", "하윤"], ["박", "지안"], ["최", "서윤"], ["정", "아윤"],
      ["강", "시아"], ["조", "아린"], ["윤", "지우"], ["장", "서연"], ["임", "가은"],
      ["한", "하은"], ["오", "소율"], ["신", "예나"], ["권", "수아"], ["황", "지아"],
      ["안", "다은"], ["송", "채원"], ["전", "유나"], ["홍", "나은"], ["문", "지유"],
      ["손", "하린"], ["배", "주아"], ["백", "예서"], ["허", "이서"], ["유", "소이"],
      ["나", "지민"], ["진", "유주"], ["지", "아라"], ["엄", "서현"], ["변", "다인"],
      ["채", "윤서"], ["원", "예원"], ["천", "지호"], ["방", "서아"], ["공", "다연"],
      ["현", "예주"], ["함", "유진"], ["편", "소민"], ["석", "나윤"], ["피", "수빈"],
      ["도", "민서"], ["차", "예진"], ["구", "시은"], ["우", "서우"], ["기", "은서"],
      ["심", "가윤"], ["곽", "지효"], ["육", "예린"], ["위", "다현"], ["추", "소윤"],
      ["성", "민지"], ["양", "효주"], ["신", "하영"], ["류", "은지"], ["명", "지수"],
      ["동", "수현"], ["라", "예슬"], ["마", "보람"], ["연", "민주"], ["봉", "가영"],
      ["부", "지혜"], ["빈", "은정"], ["사", "수진"], ["서", "현주"], ["선", "미경"],
      ["설", "영숙"], ["섭", "은영"], ["소", "지영"], ["옥", "선화"], ["온", "미나"],
      ["왕", "은주"], ["용", "혜진"], ["운", "수민"], ["음", "지현"], ["장", "유리"],
      ["김", "지안"], ["이", "서윤"], ["박", "아윤"], ["최", "시아"], ["정", "아린"],
      ["강", "지우"], ["조", "서연"], ["윤", "가은"], ["장", "하은"], ["임", "소율"],
      ["한", "예나"], ["오", "수아"], ["신", "지아"], ["권", "다은"], ["황", "채원"],
      ["안", "유나"], ["송", "나은"], ["전", "지유"], ["홍", "하린"], ["문", "주아"],
      ["손", "예서"], ["배", "이서"], ["백", "소이"], ["허", "지민"], ["유", "유주"],
      ["나", "아라"], ["진", "서현"], ["지", "다인"], ["엄", "윤서"], ["변", "예원"],
      ["채", "지호"], ["원", "서아"], ["천", "다연"], ["방", "예주"], ["공", "유진"],
      ["현", "소민"], ["함", "나윤"], ["편", "수빈"], ["석", "민서"], ["피", "예진"]
    ],
    male: [
      ["김", "도윤"], ["이", "서준"], ["박", "이준"], ["최", "은우"], ["정", "하준"],
      ["강", "지호"], ["조", "예준"], ["윤", "시우"], ["장", "유준"], ["임", "주원"],
      ["한", "건우"], ["오", "선우"], ["신", "도현"], ["권", "민준"], ["황", "지훈"],
      ["안", "연우"], ["송", "재윤"], ["전", "준서"], ["홍", "현우"], ["문", "태윤"],
      ["손", "승민"], ["배", "지석"], ["백", "윤우"], ["허", "성민"], ["유", "동현"],
      ["나", "준영"], ["진", "민성"], ["지", "승현"], ["엄", "정우"], ["변", "준호"],
      ["채", "성훈"], ["원", "상현"], ["천", "우진"], ["방", "정훈"], ["공", "성현"],
      ["현", "진우"], ["함", "동준"], ["편", "영민"], ["석", "태현"], ["피", "경민"],
      ["도", "준수"], ["차", "민규"], ["구", "성진"], ["우", "현수"], ["기", "민수"],
      ["심", "정민"], ["곽", "준혁"], ["육", "지환"], ["위", "승호"], ["추", "상훈"],
      ["성", "영준"], ["양", "기훈"], ["신", "재민"], ["류", "민석"], ["명", "동민"],
      ["동", "영호"], ["라", "성호"], ["마", "정수"], ["연", "경수"], ["봉", "진수"],
      ["부", "상민"], ["빈", "철수"], ["사", "광수"], ["서", "경호"], ["선", "대현"],
      ["설", "종수"], ["섭", "재호"], ["소", "창민"], ["옥", "태수"], ["온", "인수"],
      ["왕", "호준"], ["용", "정호"], ["운", "성수"], ["음", "현민"], ["장", "준"],
      ["김", "이준"], ["이", "은우"], ["박", "하준"], ["최", "지호"], ["정", "예준"],
      ["강", "시우"], ["조", "유준"], ["윤", "주원"], ["장", "건우"], ["임", "선우"],
      ["한", "도현"], ["오", "민준"], ["신", "지훈"], ["권", "연우"], ["황", "재윤"],
      ["안", "준서"], ["송", "현우"], ["전", "태윤"], ["홍", "승민"], ["문", "지석"],
      ["손", "윤우"], ["배", "성민"], ["백", "동현"], ["허", "준영"], ["유", "민성"],
      ["나", "승현"], ["진", "정우"], ["지", "준호"], ["엄", "성훈"], ["변", "상현"],
      ["채", "우진"], ["원", "정훈"], ["천", "성현"], ["방", "진우"], ["공", "동준"],
      ["현", "영민"], ["함", "태현"], ["편", "경민"], ["석", "준수"], ["피", "민규"]
    ]
  }
};

// Function to get random names for a specific language
function getRandomNames(language, count = 5) {
  const langNames = characterNames[language];
  if (!langNames) {
    // Fallback to English if language not found
    return getRandomNames('English', count);
  }

  const allNames = [...langNames.female, ...langNames.male];
  const shuffled = [...allNames].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

// Function to get random names by gender
function getRandomNamesByGender(language, gender, count = 3) {
  const langNames = characterNames[language];
  if (!langNames) {
    return getRandomNamesByGender('English', gender, count);
  }

  const genderNames = langNames[gender] || langNames.male;
  const shuffled = [...genderNames].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

// Make characterNames available globally - ensure it's available immediately
if (typeof window !== 'undefined') {
  window.characterNames = characterNames;
}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = characterNames;
}